<?php

/**
 * @file
 * Blellow Corporate Blocks module.
 */
/**
 * Implements hook_theme().
 */
function blellow_helper_theme() {
  return [
    'cnect_corporate_blocks_login' => [
      'variables' => [
        'corporate_login' => [],
      ],
    ],
    'cnect_corporate_blocks_register' => [
      'variables' => [
        'corporate_register' => [],
      ],
    ],
    'cnect_corporate_blocks_footer' => [
      'variables' => [
        'corporate_footer' => [],
        'custom_footer' => [],
      ],
    ],
    'cnect_corporate_blocks_newsletter' => [
      'variables' => [
        'corporate_newsletter' => [],
      ],
    ],
    'group_page_title_block' => [
      'variables' => [
        'title' => NULL
      ],
    ],
  ];
}

function blellow_helper_preprocess_menu__account(&$variables) {
  $items = $variables['items'];
  foreach ($items as $key => &$item) {
    // Hide register link.
    if ($item['url']->getRouteName() == 'user.register' && Drupal::currentUser()->isAuthenticated()) {
      unset($variables['items'][$key]);
    }
  }
}